name             'add-users'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures add-users'
long_description 'Installs/Configures add-users'
version          '0.1.0'
