name             'roger-profile'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures roger-profile'
long_description 'Installs/Configures roger-profile'
version          '0.4.0'
